name: Send LGTM Image
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ddradar/lgtm-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image-url: "https://i.imgflip.com/2c2vo7.jpg"
