name: LGTM reaction

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: LGTM Reaction 1
      uses: micnncim/action-lgtm-reaction@v0.6.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
    - name: LGTM Reaction 2
      uses: hayuna/giphy@v1.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
    - name: LGTM Reaction Tri
      uses: ddradar/lgtm-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        image-url: "https://kodeworks.no/assets/peoples/tmn.jpg"
