name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: LGTM Reaction 1
      uses: micnncim/action-lgtm-reaction@v0.6.0
    - name: LGTM Reaction 2
      uses: hayuna/giphy@v1.8
