name: Send LGTM Image
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ddradar/lgtm-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image-url: "https://www.dictionary.com/e/wp-content/uploads/2018/05/lhtm-300x300.jpg"
