name: Play Vi E Konga

on: [push, issues, issue_comment, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Spotify - Play
      uses: SvanBoxel/spotify-action@1.0.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Spotify token: Visit https://developer.spotify.com/console/get-search-item/ and click "Get token"
        token: BQDi7Dc4pE1lyZsBsWKiHbpu4kcNNNOjf2nFcTsfBwiPj3m33Q3nFBlt_uhrY0Emr3JTXr-Qwc_ryBgh-rVVvig86o2sYAswj3kPtS-WwPq56qXxUj-U_eUwlw82IaL5hn5SJnSBPFQpXuO3QPstp-2alwxl62w
        # Song to search for
        song: Vi E Konga
        # Spotify device_id (https://developer.spotify.com/documentation/web-api/reference/player/get-a-users-available-devices/)
        device_id: ${{ secrets.TRI_DEVICE_ID }}
